
- name: webservers management
  hosts: appservers
#  connection: local
  become: true
  remote_user: centos
  gather_facts: false
  vars:
    package_name: httpd
    service_name: httpd

  handlers:
  - name: restart_webservice
    service:
      name: "{{service_name}}"
      state: restarted

  tasks:
  - name: install appserver
    package:
      name: "{{package_name}}"
      state: present

  - name: start webservice
    service:
      name: "{{service_name}}"
      state: started

  - name: deploy site
    copy:
      src: ./index.html
      dest: /var/www/html/index.html
    notify:
    - restart_webservice
 
