---
# tasks file for webserver

  - name: install appserver
    package:
      name: "{{package_name}}"
      state: present

  - name: start webservice
    service:
      name: "{{service_name}}"
      state: started

  - name: deploy site
    copy:
      src: ./index.html
      dest: /var/www/html/index.html
    notify:
    - restart_webservice

  - include: user.yml

